
import javax.xml.stream.XMLInputFactory;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'uriel' at '07.12.16 20:35' with Gradle 3.2.1
 *
 * @author uriel, @date 07.12.16 20:35
 */
public class Library {
    public boolean someLibraryMethod() {
        
        return true;
    }
}
